[project]
name = "rss_to_webhook"
version = "0.0.1"
authors = [
    {name = "mymoomin"}
]
description = "Posts RSS updates to Discord webhooks"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp>=3.8.5",
    "feedparser>=6.0.10",
    "mmh3>=4.0.1",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "pymongo>=4.5.0",
]

[project.optional-dependencies]
test = [
    "mypy>=1.5.1",
    "ruff>=0.0.291",
    "black>=23.9.1",
]

[project.urls]
"Homepage" = "https://github.com/mymoomin/RSStoWebhook/"
"Bug Tracker" = "https://github.com/mymoomin/RSStoWebhook/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
mypy_path="$MYPY_CONFIG_FILE_DIR/typings"

[tool.ruff]
line-length = 88
select = [
    "E", "F", "W",  # default flake-8
    "I",            # isort
    "PGH",          # pygrep-hooks
    "UP",           # pyupgrade
    "RUF",          # Ruff-specific rules 
    "C90",          # mccabe # no new errors
    "N",            # naming # no new errors

    # Some extra flake-8 plugins
    "ANN",        # flake8-annotations # checks everything has type annotations
    # "D",          # pydocstyle # a million errors because I don't have any docstrings
    "S",            # flake8-bandit # found missing timeouts (probably good?)
    "A",            # flake8-builtins # caught shadowing `hash()` with a variable called `hash`
    "DTZ",          # flake8-datetimez # found that I was using datetime in the first place (mistake)
    "PYI",          # flake8-pyi
    "PT",           # flake8-pytest-style
    "TCH",          # flake8-type-checking # checks typechecking-only stuff is in the right place
]
src = ["src"]